### ISSUE TITLE
Enhancement: Title as a separate editable field

### ISSUE THREAD

**Issue by Amgine0** [owncloud-archive/notes-OSX-App#14]
Currently the first line of the note is assumed to be the note title.

**Comment by phedlund** [comment]
That's how the ownCloud notes app works. There is no concept of a title on the server either, it's automatically generated. Please open an issue in https://github.com/owncloud/notes/issues if you want a different behavior.

**Comment by Amgine0** [comment]
``` json
{
    "content": "$Title\n$body",
}
```

**Comment by phedlund** [comment]
And if I don't want a title? But as I said, any changes must be coordinated on the server level.

**Comment by Amgine0** [comment]
{
    "content": "( strlen($Title) ? $Title : "\n")\n$body",
}

No, they don't. This is strictly a UI issue. But it's also an enhancement request, aka 'no big thing' just something someone would like to see added.

**Comment by phedlund** [comment]
Notes on the server uses the first 100 characters of the first line as title. Regardless, the text used as title is always considered to also be part of the content.

The important thing to consider here is that what is title and content should remain consistent when syncing across devices, web interface and any other clients.

**Comment by Amgine0** [comment]
Yes. And what I suggest, as an enhancement, is that the first line (maxlen=100) be separated as a form field in the editing interface. This does not imply anything for the server, only for the editing interface.

**Comment by phedlund** [comment]
There would be a UI inconsistency if I considered the first 100 characters a title and the web UI considers it to be part of the content.

How is this app going to handle notes originally created elsewhere? Leave the title blank or use the first 100 characters that might not have been intended as a title?

I maintain that this is not a change that one client app can do in isolation.

**Comment by Amgine0** [comment]
``` php
$title = strstr( $content, "\n", true );
if ( strlen( $title ) > 100 ) {
    $title = substr( $content, 0, 100 );
}
$body = substr( $content, strlen( $title ) );
```

$title contains the title (or the first 100 characters of the first line.)
$body contains the remainder of the note.

There is a possible bug if a note is created elsewhere, and the first line has more than 100 characters, an EOL will be inserted forcing a hard break where none previously existed. This could be handled by adding a flag in the if structure, e.g. `$long_line_title = true;`, and then when concatenating the title `if ( $long_line_title == true ) { // do not add \n }else{ // add \n }` or similar.

**Comment by phedlund** [comment]
I don't know where that code comes from but it's not from https://github.com/owncloud/notes.

**Comment by Amgine0** [comment]
It is just sketching in php, because php is a simple language with easy-to-duplicate functions. The little snippets should be easily implemented in any language which can manipulate strings. Here's what I came up with in Java after a couple minutes googling for a language I have never previously tried:

``` java
String title =  null;
title = content.substring(0, content.indexOf( "\n" ) );
if ( title.length() > 100 ) {
    title = content.substring(0, 100)
}
String body = null;
body = content.substring(title.length(), content.length());
```

My apologies if that's execrable Java; it's my first touch at it and I don't even know how to execute it.

The concept is pretty straightforward: the Notes content is a text blob. The first line, or the first 100 characters of the first line, are called the title _but this is arbitrary_ and has no structural meaning. So, if you clip that out you can display it (and edit it) any way you want to, and then concatenate it back together as a text blob to send to the API.

You don't need to master the code in owncloud/notes. You only need to master the API it makes available, and the API doesn't care how you create your text blob.

**Comment by phedlund** [comment]
Implementing the API is exactly what CloudNotes does. If you read the documentation https://github.com/owncloud/notes/wiki/Notes-0.2 you will see that title is not a parameter you can set. It's something that is created on the server and returned to the client. Hence my original viewpoint that what you suggest should be coordinated and implemented on the server level.

**Comment by Amgine0** [comment]
You are correct, title is not a parameter you can **explicitly** set. 

However, you can **implicitly** set the title, because the title is the first line of the text blob you return called content.

This is why, when you update a note, it returns the new title:

``` json
{
    "id": 76,
    "content": "New content",
    "modified": 1376753464,
    "title": "New title"
}
```

Whatever **you** set the first line to will become the new title. If you want, you could set all note titles to "New Title (note edited in CloudNotes)" by simply appending " (note edited in CloudNotes)" to the first line of every note. It is up to you.
