### ISSUE TITLE
Crash while attempting to enter credentials

### ISSUE THREAD

**Issue by uzegonemad** [owncloud-archive/notes-OSX-App#2]
The app crashes whenever I attempt to enter my username or password. (server field works fine however)

These messages get logged each time I open the app, but there's nothing specific when the app crashes.

```
3/18/14 10:38:19.536 PM CloudNotes[94119]: *** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /SourceCache/AppKit/AppKit-1187.40/AppKit.subproj/NSCell.m:1532
3/18/14 10:38:19.537 PM CloudNotes[94119]: Invalid parameter not satisfying: aString != nil
```

Here's a link to the full crash report in case it's useful: https://gist.github.com/uzegonemad/9635148

**Comment by phedlund** [comment]
While I investigate try deleting the file ~/Library/Preferences/com.peterandlinda.CloudNotes.plist and all entries related to CloudNotes in the system keychain. Hopefully you should then be able to log in.

**Comment by phedlund** [comment]
Unfortunately I have been unsuccessful to get 10.8.5 to work. From now on 10.9 will be required.
