### ISSUE TITLE
make the app more like evernote

### ISSUE THREAD

**Issue by tessus** [owncloud-archive/notes-OSX-App#8]
A lot of people love Evernote, but refrain from using it because they can't use it with their own server.

It would be awesome to have an app for ownCloud which basically allows you to do the same thing as Evernote. 

This app is a good start, but it lacks several important parts:
- search field to run full text searches 
- allow rich text formatting

If I take notes it makes sense to sometimes attach a screenshot or to embed an image in the text.

Especially with the provided API it should be fairly easy to also allow sharing certain notes with users or the public.

**Comment by phedlund** [comment]
Search will be available in a future version.

Rich text editing is not supported by the server. Markdown is and will also be available in a future version.

Attachments are not supported by the server.

Sharing of notes is also not supported by the server.

You need to open issues for the Notes server app (https://github.com/owncloud/notes) to have these features implemented and made accessible to clients.

**Comment by tessus** [comment]
I'm not quite sure I understand. 

What do you mean by _Rich text editing is not supported by the server_?

Instead of creating a .txt file, just create a .rtf. MacOSX provides classes and methods to read/write rich text files.

I also don't quite understand that _Sharing of notes is also not supported by the server_.

It's nothing more than any other file in your ownCloud directory structure. Or are you telling me that there's no REST API call in ownCloud core to share files?

**Comment by phedlund** [comment]
The Mac and iOS clients interact with a REST API provided by Notes on your server (https://github.com/owncloud/notes/wiki/API-0.2). Notes on your server does not support rich text (https://github.com/owncloud/notes/issues/41) or sharing (https://github.com/owncloud/notes/issues/43). The clients do not know anything about files as everything is stored in a database on the server and also locally.

**Comment by tessus** [comment]
Ok, now I understand.

Let me ask you this: isn't there a core API call you could use to transfer a file from the Notes directory to the local system (MacOSX, iOS)? This would allow you to use whatever file type you need and which is supported by the Notes client app. I'm usually not so much into rich text, but especially if you scribble a few notes, sometimes an image says more than a thousand words...

I understand that if you had to implement a Notes API to retrieve non-text files, it would be a lot more complicated. But the ownCloud core system must have an API for file listing and transfer which you can use. I don't quite understand why you even need your own API.

Sorry for my questions, I'm just curious.
